# Simple PostgreSQL setup for development
# Usage: docker-compose -f docker-compose.dev.yml up -d

services:
  postgres:
    image: postgres:17-alpine
    container_name: fastapilaravel-postgres-dev
    environment:
      POSTGRES_DB: fastapilaravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapilaravel"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_test:
    image: postgres:17-alpine
    container_name: fastapilaravel-postgres-test
    environment:
      POSTGRES_DB: fastapilaravel_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapilaravel_test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
  postgres_test_data: