from __future__ import annotations

from typing import Any, Dict, List, Optional


class SearchClient:
    def __init__(self, app_id: str, api_key: str) -> None: ...
    
    def init_index(self, index_name: str) -> SearchIndex: ...


class SearchIndex:
    def __init__(self, client: SearchClient, name: str) -> None: ...
    
    def search(self, query: str, request_options: Optional[Dict[str, Any]] = None) -> Dict[str, Any]: ...
    def save_objects(self, objects: List[Dict[str, Any]], request_options: Optional[Dict[str, Any]] = None) -> Dict[str, Any]: ...
    def delete_objects(self, object_ids: List[str], request_options: Optional[Dict[str, Any]] = None) -> Dict[str, Any]: ...
    def clear_objects(self, request_options: Optional[Dict[str, Any]] = None) -> Dict[str, Any]: ...