from typing import Any

class BlobServiceClient:
    def __init__(self, **kwargs: Any) -> None: ...
    def get_blob_client(self, container: str, blob: str) -> Any: ...
    def get_container_client(self, container: str) -> Any: ...
    @classmethod
    def from_connection_string(cls, conn_str: str, **kwargs: Any) -> 'BlobServiceClient': ...

def generate_blob_sas(*args: Any, **kwargs: Any) -> str: ...

class BlobSasPermissions:
    def __init__(self, **kwargs: Any) -> None: ...