from datetime import datetime
from typing import Any

class Faker:
    def __init__(self, locale: str = "en_US") -> None: ...
    def email(self) -> str: ...
    def name(self) -> str: ...
    def phone_number(self) -> str: ...
    def address(self) -> str: ...
    def company(self) -> str: ...
    def text(self, max_nb_chars: int = 200) -> str: ...
    def uuid4(self) -> str: ...
    def date_time_between(self, start_date: str = "-1y", end_date: str = "now") -> datetime: ...