"""
Type stubs for psutil
"""

from typing import Any

class Process:
    def __init__(self, pid: int = ...) -> None: ...
    def memory_info(self) -> Any: ...
    def cpu_percent(self, interval: float = ...) -> float: ...

def virtual_memory() -> Any: ...
def cpu_percent(interval: float = ...) -> float: ...
def disk_usage(path: str) -> Any: ...
def pid_exists(pid: int) -> bool: ...