from typing import Any, Optional, TypeVar, Generic

T = TypeVar('T')

class Select(Generic[T]):
    def where(self, *conditions: Any) -> Select[T]: ...
    def select_from(self, *tables: Any) -> Select[T]: ...
    def order_by(self, *clauses: Any) -> Select[T]: ...
    def limit(self, limit: int) -> Select[T]: ...
    def scalar_subquery(self) -> Any: ...

def select(*columns: Any) -> Select[Any]: ...

def exists(*args: Any) -> Any: ...