from __future__ import annotations

# SQLAlchemy type stubs for better mypy support
from typing import Any, TypeVar

T = TypeVar('T')

def or_(*args: Any) -> Any:
    """SQLAlchemy or_ function type stub."""
    ...

def and_(*args: Any) -> Any:
    """SQLAlchemy and_ function type stub."""
    ...

class Column:
    def ilike(self, pattern: str) -> Any: ...
    def like(self, pattern: str) -> Any: ...
    def in_(self, values: Any) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def __lt__(self, other: Any) -> Any: ...
    def __le__(self, other: Any) -> Any: ...
    def __gt__(self, other: Any) -> Any: ...
    def __ge__(self, other: Any) -> Any: ...