from typing import Any

class func:
    @staticmethod
    def count(*args: Any) -> Any: ...
    
    @staticmethod
    def sum(column: Any) -> Any: ...
    
    @staticmethod
    def avg(column: Any) -> Any: ...
    
    @staticmethod
    def max(column: Any) -> Any: ...
    
    @staticmethod
    def min(column: Any) -> Any: ...
    
    @staticmethod
    def length(column: Any) -> Any: ...
    
    @staticmethod
    def lower(column: Any) -> Any: ...
    
    @staticmethod
    def upper(column: Any) -> Any: ...
    
    @staticmethod
    def char_length(column: Any) -> Any: ...
    
    @staticmethod
    def coalesce(*args: Any) -> Any: ...
    
    @staticmethod
    def now() -> Any: ...
    
    @staticmethod
    def current_timestamp() -> Any: ...