from typing import Any, IO, Union, Optional

def load(stream: Union[str, IO[str]], Loader: Optional[Any] = None) -> Any: ...
def load_all(stream: Union[str, IO[str]], Loader: Optional[Any] = None) -> Any: ...
def safe_load(stream: Union[str, IO[str]]) -> Any: ...
def safe_load_all(stream: Union[str, IO[str]]) -> Any: ...
def dump(data: Any, stream: Optional[IO[str]] = None, **kwargs: Any) -> Optional[str]: ...
def safe_dump(data: Any, stream: Optional[IO[str]] = None, **kwargs: Any) -> Optional[str]: ...

class YAMLError(Exception): ...
class Loader: ...
class SafeLoader(Loader): ...
class FullLoader(Loader): ...